services:
  - type: web
    name: chessscan-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: /opt/render/project/src/.venv/bin/gunicorn server:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
